### ISSUE TITLE
Driving HMT notes from a MIDI file

### ISSUE THREAD

**Issue by echolock** [andrew-lowell/HMT#1]
I've been attempting to drive Houdini from a MIDI file exported from Ableton, but the timing is off and Houdini appears much slower than the tempo of the midi file. Thus I stumbled on this toolkit. Just wondering if there's a way to use HMT in reverse: to drive Houdini from a MIDI file. I'm looking for maximum timing accuracy.

Thanks! Apologies if this is the wrong place to post this...

**Comment by andrew-lowell** [comment]
Hi Echolock,

MIDI timing is something that I've found to be pretty obscure and handeled differently in different sequencers. I for one was making a composition in Nuendo at 110 bpm only to find Houdini only exports at 90, or perhaps it's the Nuendo import.

In any event, it's a simple time-scale to fix it. I use 90 as the base and think that's a pretty good default. If you want to match the visuals exactly then hopefully using the MIDI input sop (HMT) and then scaling the x axis with a transform node to your desired bpm (use the fraction in an expression 90/sequencerbpm) and then use the time by it's position in x should work.

If you're doing time warping or bending in the sequencer that might be much more difficult. Hope this helps

**Comment by echolock** [comment]
Hi Andrew,

I'm sorry, but I'm not sure what you mean by scaling in the x-axis. I see a
string of points in the viewport, but I'm not sure what scaling does. Is it
just scaling the tempo playback of the midi file? Is there a docs page that
explains how each object works (ie: the hmt_MIDI_input SOP)? Or is this
explained in a specific video?

Trying to:
1. output a MIDI file from Ableton
2. import that MIDI file into Houdini
3. Use the MIDI to trigger events in Houdini synced with the timing of a
separate exported audio file of the same MIDI data

I appreciate your patience. I'm not new to using MIDI (been making music
for many years with Ableton and Max/MSP), but I am new to using MIDI files
and Houdini together. Didn't know that MIDI files apparently don't contain
tempo information.


Thanks!

**Comment by andrew-lowell** [comment]
The simple answer is that in the HMT, the X axis in 3D is synonymous with time (Y with pitch). But your question makes me think that a more secure grounding in how the HMT works is needed. I'd highly recommend watching at least the first few tutorials, I spent a lot of time making them and can say they're both high quality and exactly for this purpose.

**Comment by echolock** [comment]
Hi Andrew, 

Thanks for making the videos and for making this amazing toolset. So glad I found it! I watched a bunch of them yesterday and it's making much more sense now.

I did some tests using Ableton with the hope of finding an accurate way of going back and forth between the apps and you may find the results helpful. Doubling the default speed of the bpm on export from Houdini was the only way I found to make sure the export and import back into Ableton matched in length.

**FILES**
[midi_test.zip](https://github.com/andrew-lowell/HMT/files/5124092/midi_test.zip)

My Results:

Ableton (default: 120bpm, 4/4 time sig)
1. Export MIDI file (file contains time signature:4/4, no tempo. Verified by re-importing). Imports back into Ableton same length as exported.

Exporting MIDI files from Houdini
1. Import above MIDI file into hmt_MIDI_input (leave at default 90bpm)
2. Connect hmt_MIDI_input to hmt_MIDI_output (leave at default 90bpm)
4. Export MIDI file from hmt_MIDI_output
5. Import into Ableton (length of MIDI file has doubled)

Exporting MIDI files from Houdini - **CORRECT**
1. Import above MIDI file into hmt_MIDI_input (leave at default 90bpm)
2. Connect hmt_MIDI_input to hmt_MIDI_output (**change to double default: 180bpm**)
4. Export MIDI file from hmt_MIDI_output
5. Import into Ableton (length of MIDI file is same as original export)

I'm not sure if my results make sense to you or are peculiar to Ableton, but they seem a bit odd and unintuitive. I would expect to have to "set" the imported MIDI bpm in the hmt_MIDI_input and hmt_MIDI_output to match and then get the proper length in Ableton instead of needing to double it. Especially when the exported bpm (180) does not in any way match the Ableton 120bpm project tempo.

I've attached my Ableton and hip files for you to look at. Hope this helps.

Thanks again!
